# Generated by Django 4.0.4 on 2022-06-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wedensday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friday',
            field=models.ManyToManyField(to='main.friday'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monday',
            field=models.ManyToManyField(to='main.monday'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saturday',
            field=models.ManyToManyField(to='main.saturday'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sunday',
            field=models.ManyToManyField(to='main.sunday'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thursday',
            field=models.ManyToManyField(to='main.thursday'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tuesday',
            field=models.ManyToManyField(to='main.tuesday'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wedensday',
            field=models.ManyToManyField(to='main.wedensday'),
        ),
    ]
