# Generated by Django 4.0.4 on 2022-06-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_friday_monday_saturday_sunday_thursday_tuesday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.friday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='monday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.monday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='saturday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.saturday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sunday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sunday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='thursday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.thursday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tuesday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tuesday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wedensday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wedensday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.wedensday'),
        ),
    ]
