# Generated by Django 4.0.4 on 2022-06-18 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_friday_end_alter_friday_start_alter_monday_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.friday'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.monday'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.saturday'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sunday'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.thursday'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tuesday'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wedensday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.wedensday'),
        ),
    ]
