# Generated by Django 4.0.4 on 2022-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_userprofile_tuesday_userprofile_tuesdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friday',
            field=models.ManyToManyField(to='main.friday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='saturday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saturday',
            field=models.ManyToManyField(to='main.saturday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sunday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sunday',
            field=models.ManyToManyField(to='main.sunday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='thursday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thursday',
            field=models.ManyToManyField(to='main.thursday'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wedensday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wedensday',
            field=models.ManyToManyField(to='main.wedensday'),
        ),
    ]
