# Generated by Django 4.0.4 on 2022-06-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_friday_userprofile_fridays_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friday',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='monday',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='saturday',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='sunday',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='thursday',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='tuesday',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='wedensday',
            options={'ordering': ['start']},
        ),
    ]
